apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rag-dev
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: rag-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: ConfigMap
      name: rag-api-config
    patch: |-
      - op: replace
        path: /data/ENVIRONMENT
        value: dev
images:
  - name: rag-platform
    newTag: dev
